INSERT OR IGNORE INTO exercises (
  id,
  slug,
  title,
  description,
  skill_domain,
  difficulty,
  patient_profile,
  example_prompt,
  example_good_response,
  objectives,
  grading,
  tags,
  is_published,
  content,
  source_text,
  source_url,
  created_at,
  updated_at
) VALUES (
  'demo-anxiety-opening',
  'anxiety-opening',
  'Opening with anxious client',
  'Practice empathetic opening statements when a client expresses anxiety.',
  'Empathy',
  2,
  '{"name":"Jordan","age":29,"presenting":"Work anxiety"}',
  'I''m overwhelmed at work and can''t sleep.',
  'It sounds exhausting to carry that weight every day.',
  '[{"id":"reflect","label":"Reflect emotion","description":"Accurately reflect the client''s emotional tone.","rubric":{"score_min":0,"score_max":4,"anchors":[{"score":0,"meaning":"Missed the emotion entirely."},{"score":2,"meaning":"Partially reflected feelings."},{"score":4,"meaning":"Captured the emotion with warmth."}]}},{"id":"validate","label":"Validate experience","description":"Normalize the client''s reaction without fixing it.","rubric":{"score_min":0,"score_max":4,"anchors":[{"score":0,"meaning":"No validation."},{"score":2,"meaning":"Some validation but unclear."},{"score":4,"meaning":"Clear, affirming validation."}]}}]',
  '{"pass_rule":{"overall_min_score":2.5,"min_per_objective":2},"scoring":{"aggregation":"weighted_mean"}}',
  '["empathy","anxiety","opening"]',
  1,
  '{}',
  NULL,
  NULL,
  CAST(strftime('%s','now') AS INTEGER) * 1000,
  CAST(strftime('%s','now') AS INTEGER) * 1000
);
