import React, { useState } from "react";

const baseUrl = "http://127.0.0.1:8000";

export default function App() {
  const [running, setRunning] = useState(false);
  const [logs, setLogs] = useState("Gateway logs will appear here.");
  const [doctorOutput, setDoctorOutput] = useState("Run doctor checks to see status.");

  const handleToggle = () => {
    setRunning((prev) => !prev);
    setLogs((prev) => `${prev}\n${new Date().toLocaleTimeString()} toggled gateway`);
  };

  const handleDoctor = () => {
    setDoctorOutput("[doctor] ffmpeg: missing\nFix: brew install ffmpeg");
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(baseUrl);
  };

  return (
    <div className="app">
      <header>
        <h1>Local Runtime Launcher</h1>
        <p>Manage your local OpenAI-compatible gateway.</p>
      </header>
      <section className="card">
        <div className="row">
          <div>
            <h2>Gateway</h2>
            <p>Status: {running ? "Running" : "Stopped"}</p>
          </div>
          <button className="primary" onClick={handleToggle}>
            {running ? "Stop" : "Start"}
          </button>
        </div>
        <div className="row">
          <div>
            <span className="label">Base URL</span>
            <code>{baseUrl}</code>
          </div>
          <button onClick={handleCopy}>Copy</button>
        </div>
      </section>

      <section className="card">
        <h2>Defaults</h2>
        <div className="grid">
          <label>
            LLM Model
            <select>
              <option>local/llm/qwen3-mlx</option>
            </select>
          </label>
          <label>
            TTS Model
            <select>
              <option>local/tts/kokoro</option>
            </select>
          </label>
          <label>
            STT Model
            <select>
              <option>local/stt/faster-whisper</option>
            </select>
          </label>
        </div>
        <p className="disclosure">
          AI-generated TTS audio disclosure: all synthesized voices are generated by artificial intelligence.
        </p>
      </section>

      <section className="card">
        <h2>Logs</h2>
        <pre>{logs}</pre>
      </section>

      <section className="card">
        <div className="row">
          <h2>Doctor</h2>
          <button onClick={handleDoctor}>Run Doctor</button>
        </div>
        <pre>{doctorOutput}</pre>
      </section>
    </div>
  );
}
